// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// railcom_cutout //
// -------------- //

#define railcom_cutout_wrap_target 0
#define railcom_cutout_wrap 5

static const uint16_t railcom_cutout_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0
    0xe001, //  1: set    pins, 1         side 0
    0xa027, //  2: mov    x, osr          side 0
    0x0e43, //  3: jmp    x--, 3          side 0 [14]
    0xe000, //  4: set    pins, 0         side 0
    0xc000, //  5: irq    nowait 0        side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program railcom_cutout_program = {
    .instructions = railcom_cutout_program_instructions,
    .length = 6,
    .origin = -1,
};

static inline pio_sm_config railcom_cutout_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + railcom_cutout_wrap_target, offset + railcom_cutout_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif
