name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.10
      with:
        cmake-version: '3.13.x'
    - name: Set up Google Test
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
    - name: Build and run tests
      run: |
        cd tests
        cmake .
        make
        ./railcom_tests
