name: Continuous Integration

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install RP2040 Platform and Libraries
        run: |
          arduino-cli config init
          arduino-cli config set board_manager.additional_urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
          arduino-cli core update-index
          arduino-cli core install rp2040:rp2040@3.1.1
          arduino-cli lib install NmraDcc

      - name: Regenerate railcom.pio.h
        run: |
          PIOASM_PATH=$(find /home/runner/.arduino15/packages/rp2040/tools -name pioasm -type f)
          echo "Found pioasm at $PIOASM_PATH"
          $PIOASM_PATH -o c-sdk src/railcom.pio src/railcom.pio.h

      - name: Compile All Sketches
        run: |
          SKETCHES=(
            "examples/AccessoryDecoderDummy"
            "examples/AccessoryDecoderNmra"
            "examples/CommandStation"
            "examples/FunctionDecoderDummy"
            "examples/LocomotiveDecoderDummy"
            "examples/LocomotiveDecoderNmra"
          )

          for sketch in "${SKETCHES[@]}"; do
            echo "Compiling $sketch"
            arduino-cli compile --fqbn rp2040:rp2040:rpipico --libraries="." "$sketch"
            if [ $? -ne 0 ]; then
              echo "Failed to compile $sketch"
              exit 1
            fi
          done
      - name: Run Web App Tests
        run: |
          npm install -g npm@10.8.1
          cd tools
          npm install
          npm test
